Repository hyphacoop/handbook, pull requests merged in 2020-03, with the labels that each got.

#50 Added mentioned of remittance schedule.
  finance.md
Labels: wg:finance

#52 Add new Social Media Steward role definition
  roles.md
Labels: wg:business-planning

#43 Initial pass at glossary
  SUMMARY.md
  glossary.md
  reading-pool.md
Labels: [priority-★★☆], enhancement, wg:ops

#55 Add clip term to glossary
  glossary.md
Labels: [priority-★☆☆], wg:ops

#56 Add guide for updating labels
  guides.md
Labels: [priority-★★☆], wg:infrastructure, wg:operations

#61 Add link to HelloSign example
  guides.md
Labels: [priority-★☆☆], wg:operations

#54 Add guide for setting up email inboxes (admin + user)
  .gitignore
  guides.md
  images/email-mailbox-1.png
  images/email-mailbox-2.png
  images/email-mailbox-3.png
  images/email-mailbox-4.png
  images/email-mailbox-5.png
Labels: [priority-★★☆], wg:infrastructure
