Repository hyphacoop/handbook, pull requests merged in 2020-02, with the labels that each got.

#38 Add guide for storing sensitive information
  guides.md
  reading-pool.md
Labels: wg:infra, wg:ops

#20 Project proposal process doc
  guides.md
  reading-pool.md
Labels: [priority-★★★], wg:governance

#48 Headerize OKR subsections
  okrs.md
Labels: wg:ops
